package cn.elytra.translatools.internal

import cn.elytra.translatools.api.annotation.PathMarker
import cn.elytra.translatools.api.project.IndexedFile
import cn.elytra.translatools.api.project.Project
import cn.elytra.translatools.api.project.hashMD5
import cn.elytra.translatools.internal.platform.Paratranz
import cn.elytra.translatools.internal.utils.forEachCoroutineScope
import cn.elytra.translatools.internal.utils.groupEntriesBy
import kotlinx.serialization.Serializable
import org.jetbrains.annotations.TestOnly
import java.nio.file.Path
import kotlin.io.path.Path

internal class RemoteAssociatedIndexedFileStorage(
    private val local: List<IndexedFile>,
    private val remote: List<Paratranz.File>,
) {
    @Serializable
    data class PathInformation(
        var local: IndexedFile? = null,
        var remote: Paratranz.File? = null,
    ) {
        operator fun plus(other: PathInformation): PathInformation =
            PathInformation(
                local ?: other.local,
                remote ?: other.remote,
            )
    }

    @get:TestOnly
    internal val pathIndexed: Map<
        @PathMarker.Relative(relativeTo = "sourcesDirectory")
        Path,
        PathInformation,
    > =
        buildMap {
            remote.forEach { remote ->
                this.merge(Path(remote.name).normalize(), PathInformation(remote = remote), PathInformation::plus)
            }
            local.forEach { local ->
                this.merge(local.path.normalize(), PathInformation(local = local), PathInformation::plus)
            }
        }

    enum class Status {
        LOCAL_MISSING,
        REMOTE_MISSING,
        MODIFIED,
        UNMODIFIED,
        BOTH_MISSING,
    }

    val paths get() = pathIndexed.keys.toList()

    fun getLocal(path: Path): IndexedFile? = pathIndexed[path]?.local

    fun getRemote(path: Path): Paratranz.File? = pathIndexed[path]?.remote

    context(project: Project)
    fun getStatus(path: Path): Status {
        val info = pathIndexed[path] ?: return Status.BOTH_MISSING
        val (local, remote) = info
        return getStatus(local, remote)
    }

    context(project: Project)
    private fun getStatus(
        local: IndexedFile?,
        remote: Paratranz.File?,
    ): Status {
        if (local == null) return Status.LOCAL_MISSING
        if (remote == null) return Status.REMOTE_MISSING
        // FIXME: it's not supposed to comparing the sources, but the translation generated by the handlers
        return if (local.hashMD5() == remote.hash) {
            Status.UNMODIFIED
        } else {
            Status.MODIFIED
        }
    }

    context(project: Project)
    private fun getStatus(information: PathInformation) = getStatus(information.local, information.remote)

    /**
     * Return all tracked paths grouped by their [status][Status].
     *
     * It's guaranteed that the information will be **both non-null** if [Status.MODIFIED] and [Status.UNMODIFIED],
     * **local non-null** if [Status.REMOTE_MISSING], **remote non-null** if [Status.LOCAL_MISSING].
     */
    context(project: Project)
    fun allByStatus(): Map<
        Status,
        Map<
            @PathMarker.Relative(relativeTo = "sourcesDirectory")
            Path,
            PathInformation,
        >,
    > =
        pathIndexed.groupEntriesBy { (_, information) -> getStatus(information) }
}

internal inline fun Map<Path, RemoteAssociatedIndexedFileStorage.PathInformation>.forEachDecomposited(
    block: (path: Path, local: IndexedFile?, remote: Paratranz.File?) -> Unit,
) = forEach { (path, information) ->
    block(path, information.local, information.remote)
}

internal suspend inline fun Map<Path, RemoteAssociatedIndexedFileStorage.PathInformation>.forEachDecompositedSuspend(
    crossinline block: suspend (path: Path, local: IndexedFile?, remote: Paratranz.File?) -> Unit,
) = forEachCoroutineScope { (path, information) ->
    block(path, information.local, information.remote)
}
